In [1]:
import torch
import torch.nn as nn

In [17]:
x = torch.tensor([[1.0, 1.0, 2.0],[0.0, 0.0, 2.0]])
y = torch.tensor([[10.0, 2.0, 91.0],[0.0, 2.0, 0.0]])

x_norms = torch.linalg.vector_norm(x, dim = 1)
y_norms = torch.linalg.vector_norm(y, dim = 1)
print(x_norms)
print(y_norms)

tensor([2.4495, 2.0000])
tensor([91.5696,  2.0000])


In [6]:
x = torch.tensor([4.0, 5.0, 6.0])
x = torch.reshape(x, (-1,1))

y = torch.tensor([2.0, 5.0, 12.0])
y = torch.reshape(y, (-1, 1))

matrix = torch.tensor([[11.0, 2.0, 8.0],[0.4, 2.0, 0.3],[0.4, 2.0, 0.3]])

z = x / y
print(z)
print(matrix)
matrix *= z
print(matrix)


tensor([[2.0000],
        [1.0000],
        [0.5000]])
tensor([[11.0000,  2.0000,  8.0000],
        [ 0.4000,  2.0000,  0.3000],
        [ 0.4000,  2.0000,  0.3000]])
tensor([[22.0000,  4.0000, 16.0000],
        [ 0.4000,  2.0000,  0.3000],
        [ 0.2000,  1.0000,  0.1500]])
